security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_API:
            - ROLE_USER
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_API
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern:    ^/api/v1
            fos_oauth:  true
            stateless:  true
            anonymous:  false
        main:
            pattern: ^/
            form_login:
                login_path:             /user/login
                check_path:             /user/login_check
                provider:               fos_userbundle
                csrf_token_generator:   security.csrf.token_manager
            logout:
                path:   /user/logout
                target: /
            anonymous:  true
        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
    access_control:
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, role: ROLE_ADMIN }
        - { path: ^/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/v2/auth_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app, role: ROLE_ADMIN }